# Generated by Django 5.0 on 2023-12-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ape1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='pago',
            field=models.FloatField(),
        ),
    ]
