# Generated by Django 5.0 on 2023-12-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ape1', '0002_alter_empleado_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='numHoraTrabajada',
            new_name='horas_trabajadas',
        ),
    ]
