# Generated by Django 5.0 on 2023-12-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ape1', '0003_rename_numhoratrabajada_empleado_horas_trabajadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='horas_trabajadas',
            new_name='horasTrabajadas',
        ),
    ]
