# Generated by Django 4.2.5 on 2023-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='talla_calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(to='aplicacion1.talla_calzado'),
        ),
    ]
