# Generated by Django 4.2.5 on 2023-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_talla_calzado_producto_tallas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='talla_calzado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(to='aplicacion1.talla'),
        ),
    ]
