# Generated by Django 4.2.5 on 2023-10-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_talla_delete_talla_calzado_alter_producto_tallas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ManyToManyField(to='aplicacion1.imagenproducto'),
        ),
    ]
