# Generated by Django 4.2.5 on 2023-10-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0005_imagenproducto_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
        migrations.AddField(
            model_name='imagenproductos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
