# Generated by Django 4.2.5 on 2023-10-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0006_imagenproductos_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagenProductos',
            new_name='ImagenProducto',
        ),
    ]
